### ISSUE TITLE
Incorrect model loading

### ISSUE THREAD

**Issue by agemagician** [cybertronai/transformer-xl#15]
Hello,

I think you have 3 issues in mode loading:-

1. If someone loaded a model from a specific checkpoint, the model will be reloaded from best-model. It will simply override it.

2. The loading of best-model is written after the "train" function. This simply means it will never execute.

3. loading best-model assumes the checkpoint will exist in all nodes not only the first node.
I would recommend to take a look at:
https://pytorch.org/tutorials/intermediate/ddp_tutorial.html
How to map it from GPU0 at master node to all other nodes.

Thanks.

**Comment by yaroslavvb** [comment]
1&2.  Checkpointing in master branch is left over from original transformer. It's not used in the examples, and it actually doesn't even work because of interaction with FP16 optimizer . I've redone checkpointing in this branch -- https://github.com/cybertronai/transformer-xl/tree/checkpoint

3. The newer version only does checkpoint saving/loading in the 0 worker, and then broadcasts parameters to the rest of the workers

**Comment by agemagician** [comment]
Great, waiting for the merge :)
